# Generated by Django 5.1.6 on 2025-05-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationEmailRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("activation_link", models.TextField(blank=True, null=True)),
                ("user_created", models.BooleanField(default=False)),
                ("user_activated", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Registration Email Record",
                "verbose_name_plural": "Registration Email Records",
                "ordering": ["-timestamp"],
            },
        ),
    ]
