# Generated by Django 5.1.6 on 2025-04-08 22:36

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checker", "0003_add_performance_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="CMURegistry",
            fields=[
                (
                    "cmu_id",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "raw_data",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="component",
            options={"ordering": ["-delivery_year"]},
        ),
        migrations.AlterField(
            model_name="component",
            name="additional_data",
            field=models.JSONField(
                default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
        migrations.AlterField(
            model_name="component",
            name="auction_name",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="component",
            name="component_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="component",
            name="description",
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name="component",
            index=models.Index(
                fields=["company_name", "delivery_year"], name="comp_delivery_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="component",
            index=models.Index(
                fields=["location", "company_name"], name="loc_comp_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="component",
            index=models.Index(
                fields=["auction_name", "delivery_year"], name="auction_year_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="component",
            index=models.Index(
                fields=["company_name", "location"], name="vital_search_idx"
            ),
        ),
    ]
