# Generated by Django 5.1.6 on 2025-04-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checker", "0004_cmuregistry_alter_component_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="derated_capacity_mw",
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
    ]
