# Generated by Django 5.1.6 on 2025-04-16 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checker", "0005_component_derated_capacity_mw"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="geocoded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="component",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="component",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
