# Generated by Django 5.1.6 on 2025-04-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checker", "0006_component_geocoded_component_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="component",
            name="latitude",
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="component",
            name="longitude",
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name="component",
            index=models.Index(fields=["latitude", "longitude"], name="spatial_idx"),
        ),
    ]
