# Generated by Django 5.1.6 on 2025-05-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checker", "0007_alter_component_latitude_alter_component_longitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="county",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="outward_code",
            field=models.CharField(blank=True, db_index=True, max_length=5, null=True),
        ),
    ]
