# Generated by Django 5.1.6 on 2025-05-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checker", "0008_component_county_component_outward_code"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="component",
            index=models.Index(
                fields=["technology", "company_name"], name="tech_comp_idx"
            ),
        ),
    ]
