# Generated by Django 5.1.6 on 2025-05-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checker", "0009_component_tech_comp_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="component",
            index=models.Index(
                fields=["delivery_year", "location"], name="year_loc_idx"
            ),
        ),
    ]
